name: wood_lightning_module
_target_: wood-classification.modules.wood_lightning_module.WoodLightningModule

model: ${checkpoints}
num_classes: ${data.num_classes}
learning_rate: 2e-4
use_pretrained: True

