name: wood_lightning_module
_target_: wood-classification.modules.wood_lightning_module.WoodLightningModule

model: ${models}
num_classes: ${data.num_classes}
learning_rate: 1e-4
use_pretrained: True

