early_stop_callback:
  monitor: 'val_loss'
  patience: 3
  verbose: False
  mode: 'min'

checkpoint_callback:
  monitor: 'val_loss'
  dirpath: './models'
  filename: 'model-{epoch:02d}-{val_loss:.2f}'
  save_top_k: 3
  mode: 'min'

model_summary_callback:
  max_depth: 1

timer:
  duration: '00:06:00:00'

trainer:
  max_epochs: 100
  gpus: 1
  callbacks: [early_stop_callback, checkpoint_callback, model_summary_callback, timer]

defaults:
  - data: wood_data_module
  - models: wimcnn_model
  - modules: wood_lightning_module
